// 跨游戏工具:把 monorepo 布局组装成 Capacitor webDir(www/)。
// 用法:在游戏目录下跑 `node ../../tools/build-www.cjs`(或传游戏目录为参数)。
// 做三件事:拷 engine/ + 游戏静态目录 → 重写 index.html 的 ../../engine/ 路径 → 自校验。
const fs = require('fs');
const path = require('path');

const GAME = path.resolve(process.argv[2] || process.cwd());
const ROOT = path.join(__dirname, '..');
const WWW = path.join(GAME, 'www');

if (!fs.existsSync(path.join(GAME, 'index.html'))) {
  throw new Error('not a game dir (no index.html): ' + GAME);
}

function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dst, e.name);
    if (e.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

fs.rmSync(WWW, { recursive: true, force: true });
fs.mkdirSync(WWW, { recursive: true });

copyDir(path.join(ROOT, 'engine'), path.join(WWW, 'engine'));
// 游戏静态目录:有哪个拷哪个(mines 没有 css/,snake 有)
// ⚠ 'data' 是 connect4 加的（3.6 MB 开局库）。⛔ 漏了它出包会是**静默**的灾难：
//   页面照常起、AI 却在玩家落第一子后永久停摆，而提示/复盘/精准度/妙手/课程
//   全部因为 analysis 的 bookOk() 闸而**什么都不显示**，一处报错都没有。
//   ⚠ 其它游戏没有 data/ 目录 ⇒ 下面的 existsSync 会跳过，对它们是 no-op。
for (const dir of ['js', 'css', 'assets', 'locales', 'fonts', 'data']) {
  const src = path.join(GAME, dir);
  if (fs.existsSync(src)) copyDir(src, path.join(WWW, dir));
}

// 跨游戏共享素材:游戏 package.json 的 wwwExtras [{from,to}](from 相对仓库根)。
// 场景:solitaire 的天使图鉴复用 snake 的 assets/angels(网页端走相对路径同源,
// 出包时才需要真拷进 www —— 仓库里绝不存两份 26MB)。
try {
  const pkg = JSON.parse(fs.readFileSync(path.join(GAME, 'package.json'), 'utf8'));
  for (const ex of pkg.wwwExtras || []) {
    const src = path.join(ROOT, ex.from);
    if (!fs.existsSync(src)) throw new Error('wwwExtras missing: ' + ex.from);
    copyDir(src, path.join(WWW, ex.to));
    console.log('wwwExtras:', ex.from, '->', ex.to);
  }
} catch (e) { if (String(e).includes('wwwExtras')) throw e; }

// ⛔⛔ 原生包里绝不许有「运行时从远程拉 JS 执行」的代码 —— 哪怕它在原生上永不执行。
//   2026-08-07 实锤：Dungeon Sweep(minesweeper) 1.0 被苹果按 **Guideline 5.6 开发者行为准则**
//   拒审，原话是「app 含有似乎在审核过程中被刻意隐藏的功能 / 与欺诈行为相关的异常模式」。
//   包里唯一对得上这句话的就是 engine/portal.js：它会 createElement('script') 从
//   html5.api.gamedistribution.com 拉 SDK，而 `active` 要求 !Platform.isNative
//   ⇒ **审核员在设备上永远看不到它**，开关还是外部可拨的(?portal=gd / window.__PORTAL__)。
//   意图无辜(网页版发游戏门户用)，但那个意图**在二进制里看不出来**，读起来就是
//   「可被外部开关激活、下载并执行第三方任意代码、且审核期不可见」。
//   ⇒ 出包时把它换成惰性 stub。⛔ 不能直接不拷：ads.js 会碰 `Portal.active`
//     (AdMob 插件缺失时原生也会走进 web 分支) ⇒ 文件没了就是 ReferenceError 白屏。
//   门户 SDK 只在网页/门户版存在，走 games/*/index.html 原文，与 iOS/Android 包无关。
const PORTAL_STUB = `// portal.js — NATIVE BUILD STUB (generated by tools/build-www.cjs)
// 游戏门户(GameDistribution/CrazyGames/Poki)广告适配是**纯网页**的事。
// 原生包里塞的是这份惰性替身：零远程 URL、零动态脚本、零休眠分支。
// 网页版的真实实现见仓库的 engine/portal.js。
const Portal = {
  active: false,
  id: null,
  boot() {},
  showInterstitial() { return Promise.resolve(); },
  showRewarded() { return Promise.resolve(false); },
};
`;
fs.writeFileSync(path.join(WWW, 'engine', 'portal.js'), PORTAL_STUB);

const html = fs.readFileSync(path.join(GAME, 'index.html'), 'utf8')
  .replace(/\.\.\/\.\.\/engine\//g, 'engine/');
fs.writeFileSync(path.join(WWW, 'index.html'), html);

// 地面真值:重写真的生效、关键文件真的在
const out = fs.readFileSync(path.join(WWW, 'index.html'), 'utf8');
if (out.includes('../../engine/')) throw new Error('engine path rewrite failed');
for (const f of ['engine/canvas.js', 'js/main.js', 'locales/en.json']) {
  if (!fs.existsSync(path.join(WWW, f))) throw new Error('missing in www: ' + f);
}
// ⭐⭐ 自校验:**代码 fetch 的相对路径,其顶层目录必须真的进了包**。
//   ⚠ 这条是 2026-08-07 的 code review 抓出来的一整类静默失败:
//     · connect4 的 data/book-classic.bin(3.6 MB 开局库)不在拷贝清单里 ⇒ 出包后
//       AI 在玩家落第一子后永久停摆,提示/复盘/精准度/妙手/课程全部什么都不显示;
//     · solitaire 的 data/pool-draw*.json(可解池,它的核心卖点)同样漏了,而
//       pool.js 的 fetch 外面就是 catch(e){} ⇒ **三个已上架版本都在静默降级**。
//   两次都是「本地全绿、包里没有」——⛔ 没有任何一条既有测试碰得到它。
{
  const jsDir = path.join(GAME, 'js');
  const refs = new Set();
  if (fs.existsSync(jsDir)) {
    for (const fn of fs.readdirSync(jsDir).filter(x => x.endsWith('.js'))) {
      // ⚠ **必须剥掉注释再扫**：本仓注释里到处是「见 tools/gen-sfx.js」这类**文档路径**，
      //   不剥的话它们会被当成运行时资源，报一堆 tools/ 不在包里的误报（实测 connect4
      //   与 blockblast 都中）。同 test-threats/test-review 的源码级检查那条老做法。
      const src = fs.readFileSync(path.join(jsDir, fn), 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
      // ⚠ 两种写法都要扫，⛔ 只扫 fetch( 是不够的：
      //   · solitaire 直接 `fetch('data/pool-draw1.json')`
      //   · connect4 在 worker 里写成常量 `const BOOK_URL = '../data/book-classic.bin'`
      //     再交给 Book.load() —— 只扫 fetch( 的话**它一个都抓不到**，而它正是
      //     3.6 MB 开局库那条（本条门禁的头号目标）。
      //   ⇒ 扫所有**看起来像相对资源路径的字符串字面量**（带 / 且带扩展名）。
      const RE = /[`'"]((?:\.\.\/)*[A-Za-z0-9_-]+\/[^`'"()\s]*\.[A-Za-z0-9]{2,5})[`'"]/g;
      for (const m of src.matchAll(RE)) {
        const p = m[1];
        if (/^(https?:)?\/\//.test(p) || p.startsWith('/')) continue;   // 绝对/跨域的不管
        // ⚠ 去掉开头的 ../（worker 在 js/ 下，路径是相对它自己的）
        const rel = p.replace(/^(\.\.\/)+/, '');
        const top = rel.split('/')[0];
        // ⛔ engine/ 由上面的 copyDir 整份带上，js/ 是自己 ⇒ 不必查
        if (top && top !== 'engine' && top !== 'js' && rel.includes('/')) refs.add(top);
      }
    }
  }
  for (const dir of refs) {
    if (!fs.existsSync(path.join(WWW, dir))) {
      throw new Error('代码 fetch 了 ' + dir + '/ 但它没进 www —— '
        + '把它加进上面那个拷贝清单,或给游戏 package.json 加 wwwExtras。'
        + '⛔ 这类漏拷在包里是**静默失效**(fetch 404 常被 catch 吞掉)');
    }
  }
  if (refs.size) console.log('fetch 依赖的目录都在包里:', [...refs].join(', '));
}

// 共享 UI 图标库(engine/assets/ui/)必须整份进包 —— 它是 engine 的一部分,靠上面那次
// copyDir(engine) 自动带上。⚠ 但页面里的图标路径是**运行时**由 engine/ui-icons.js
// 从脚本标签反推的(网页 ../../engine/ vs 包内 engine/),路径错了不会报错、只会满屏
// 退回 emoji ⇒ 这里把「库在不在」钉死,少一层静默失败。
if (fs.existsSync(path.join(ROOT, 'engine', 'assets', 'ui'))) {
  const uiDir = path.join(WWW, 'engine', 'assets', 'ui');
  if (!fs.existsSync(path.join(uiDir, 'manifest.json'))) throw new Error('missing in www: engine/assets/ui/manifest.json');
  const n = fs.readdirSync(uiDir).filter(f => f.endsWith('.webp')).length;
  if (n < 10) throw new Error('engine/assets/ui 只拷进 ' + n + ' 张,像是没拷全');
}
// ⛔⛔ 出包禁忌扫描：包里不许有「动态下发/执行远程代码」的任何痕迹（见上面 PORTAL_STUB 那段的原委）。
//   苹果对二进制做静态分析，看的是**代码里有什么**，不是**运行时会不会走到**。
//   一条休眠的远程 script 注入 = Guideline 5.6「审核期被隐藏的功能」，是账号级风险，
//   不是单个 app 的内容问题 —— 已上架的版本也跑不掉。
{
  const BANNED = [
    [/createElement\(\s*['"]script['"]\s*\)/, '动态创建 <script>（远程代码注入）'],
    [/\beval\s*\(/,                            'eval()'],
    [/\bnew\s+Function\s*\(/,                  'new Function()'],
    [/gamedistribution\.com/,                  '游戏门户 SDK 域名 GameDistribution'],
    [/crazygames\.com/,                        '游戏门户 SDK 域名 CrazyGames'],
    [/poki-sdk|game-cdn\.poki\.com/,           '游戏门户 SDK 域名 Poki'],
  ];
  const hits = [];
  (function walk(dir) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) { walk(p); continue; }
      if (!/\.(js|html|mjs|cjs)$/.test(e.name)) continue;
      const src = fs.readFileSync(p, 'utf8');
      for (const [re, why] of BANNED) {
        const m = src.match(re);
        if (m) hits.push('  ' + path.relative(WWW, p) + ' → ' + why + '（' + m[0] + '）');
      }
    }
  })(WWW);
  if (hits.length) {
    throw new Error('⛔ 出包禁忌：www 里含有动态/远程代码执行的痕迹，苹果 5.6 会按'
      + '「审核期被隐藏的功能」拒审（minesweeper 1.0 已因此被拒）：\n' + hits.join('\n')
      + '\n把它挪到只在网页构建里存在，或像 portal.js 那样出包时换成惰性 stub。');
  }
}

console.log('www assembled OK (' + path.basename(GAME) + '):', fs.readdirSync(WWW).join(', '));
